# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeScore < Formula
  desc ""
  homepage "https://kube-score.com/"
  version "1.16.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zegl/kube-score/releases/download/v1.16.0/kube-score_1.16.0_darwin_arm64.tar.gz"
      sha256 "d5d25146f7433c01bc12f215bfccb7e981482b1038198c9d48d1d1c6c2962e8e"

      def install
        bin.install "kube-score"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zegl/kube-score/releases/download/v1.16.0/kube-score_1.16.0_darwin_amd64.tar.gz"
      sha256 "0fc6c378928a6f3f4b5dd8ba4980c25aab07a341b61d020a95f9ce48e6abb641"

      def install
        bin.install "kube-score"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/zegl/kube-score/releases/download/v1.16.0/kube-score_1.16.0_linux_armv6.tar.gz"
      sha256 "3796331195a4c03f971cc8ed0f719c2ad4d79b9a5dfb11c9357c85ccf195862d"

      def install
        bin.install "kube-score"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zegl/kube-score/releases/download/v1.16.0/kube-score_1.16.0_linux_arm64.tar.gz"
      sha256 "c99f2df47e19b0febd3e64a2ca9e24b14eba0d35d8a6da450db159e9f408584e"

      def install
        bin.install "kube-score"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zegl/kube-score/releases/download/v1.16.0/kube-score_1.16.0_linux_amd64.tar.gz"
      sha256 "2de8bab50e56c29982ac296c145821f3cfda6a771d46430025ffac4211d085dd"

      def install
        bin.install "kube-score"
      end
    end
  end
end
