# This file was generated by GoReleaser. DO NOT EDIT.
class KubeScore < Formula
  desc ""
  homepage "https://kube-score.com/"
  version "1.6.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zegl/kube-score/releases/download/v1.6.0/kube-score_1.6.0_darwin_amd64.tar.gz"
    sha256 "ae5d238658aced15a7d71f2dfbac3b17d9e7004ce2b460e248939923035e857b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/zegl/kube-score/releases/download/v1.6.0/kube-score_1.6.0_linux_amd64.tar.gz"
      sha256 "c455ff62f1d84f5e48b6731e5969e1301db773f8a3b9963499481064b6784e28"
    end
  end

  def install
    bin.install "kube-score"
  end
end
